### ISSUE TITLE
ModuleNotFoundError: No module named 'object_detection'

### ISSUE THREAD

**Issue by GodIsAWord** [MoerkerkeLander/camera-feed-object-detector-tf-serve#1]
why,bro,how can I solve the problem

**Comment by LanderMoerkerke** [comment]
A bit more information is needed to solve your problem.
bro

**Comment by GodIsAWord** [comment]
w8 a min

**Comment by GodIsAWord** [comment]
@MoerkerkeLander  why locking [dev-packages] dependencies is so slow :(

**Comment by GodIsAWord** [comment]
@MoerkerkeLander  Do you have Pipfile.lock?my friend

**Comment by LanderMoerkerke** [comment]
Pipfile.lock isn't necessary, I cloned the repo and installed the requirements. So the versions should match up. 
Are you running the script from the root of the project?
